global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi:8000']

  # - job_name: 'rabbitmq'
  #   static_configs:
  #     - targets: ['rabbitmq:15692']

  # Redis 메트릭 (redis_exporter 필요)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']

  # Nginx 메트릭 (nginx-prometheus-exporter 필요)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx_exporter:9113']